extinction:
  airmass: 'Kasten-Young'

noise:
  distribution: 'normal'
  parameters:
    sigma: 3
    mean: 10

projection:
  formula: 'Borovička'
  parameters:
    x0: 800
    y0: 600
    a0: 0
    a: 0
    f: 0
    v: 300
    s: 0
    d: 0
    p: 0
    d: 0
    epsilon: 0
    e: 0
