#!/usr/bin/env python
import argparse
import logging
import os
import time
from pathlib import Path
from typing import Optional

import argparsedirs
import dotmap
import numpy as np

from multiprocessing import Pool

import yaml
from astropy.coordinates import EarthLocation
from astropy.time import Time
from astropy import units as u

from scalyca import Scalyca

from demeteor.projections import Projection, BorovickaProjection
from demeteor.catalogue import Catalogue
from demeteor.projections.shifters import ScalingShifter

from models.observer import Observer
from models.skypointsource import SkyPointSource
from models.scene import Scene


np.set_printoptions(edgeitems=100)
log = logging.getLogger('root')
VERSION = '0.1.1'


class MeteorRenderer(Scalyca):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.catalogue: Optional[Catalogue] = None
        self.projection: Optional[Projection] = None
        self.scaler = None

    def add_arguments(self):
        self.add_argument('source', type=argparse.FileType('r'),
                          help="Source file (generated by `observe`)")
        self.add_argument('camera', type=argparse.FileType('r'),
                          help="Camera configuration file (YAML)")
        self.add_argument('-c', '--catalogue', type=argparse.FileType('r'), default=None,
                          help="Star catalogue file (DSV); the one demeteor ships if not given")
        self.add_argument('-p', '--projection', type=argparse.FileType('r'))
        self.add_argument('output_dir', type=argparsedirs.WriteableDirType,
                          help="Output directory for PNG files")
        self.add_argument('-j', '--cores', type=int, default=4,
                          help="Number of CPU cores to use")

    def initialize(self):
        source = yaml.safe_load(self.args.source)
        # 'sources', which is what observe.py writes. This read 'fragments' and then never
        # converted them, and main() went on to use a bare `fragments` that was never defined at
        # all -- so the renderer could not have run since observe.py's output was last renamed.
        self.fragments = [SkyPointSource.load_dict(fragment) for fragment in source['sources']]
        self.observer = Observer.load_dict(source['observer'])
        # The catalogue demeteor ships -- HYG 4.4 to visual magnitude 6 -- unless one is named.
        # config/catalogues/*.tsv are in the format amosutils read, two columns and no names, and
        # demeteor's has six; one catalogue across the ecosystem is also one fewer thing that can
        # be a different catalogue in the simulation than in the fit.
        self.catalogue = (Catalogue.bundled() if self.args.catalogue is None
                          else Catalogue(self.args.catalogue))

        if self.args.projection:
            self.projection = Projection.from_dict(yaml.safe_load(self.args.projection))
        else:
            self.projection = BorovickaProjection()
            logging.warning("No Projection specified, using default")

        self.camera = dotmap.DotMap(yaml.safe_load(self.args.camera), _dynamic=False)
        self.camera.padding.start *= u.s
        self.camera.padding.end *= u.s

        self.scaler = ScalingShifter(x0=self.camera.pixels.x0, y0=self.camera.pixels.y0,
                                     xs=self.camera.pixels.xs / 1000, ys=self.camera.pixels.ys / 1000)

        self.output_dir = Path(self.args.output_dir)

        if self.args.cores:
            self.config.cores = self.args.cores

    def main(self):
        self.t0 = Time(self.config.start)
        self.dt = 0.05 * u.s
        self.times = self.t0 + np.arange(-self.camera.padding.start / self.dt,
                                         self.config.count + 1 + self.camera.padding.end / self.dt) * self.dt

        args = [(self.camera.detector.xres, self.camera.detector.yres,
                 self.projection, self.scaler,
                 self.observer.location, self.catalogue, self.fragments, i, time, self.output_dir)
                for i, time in enumerate(self.times)]
        pool = Pool(self.config.cores)
        log.info(f"Rendering {len(self.fragments)} fragment(s) at {len(self.times)} times "
                 f"on {self.config.cores} cores")
        pool.starmap(render, args, 1)


def render(xres: int, yres: int,
           projection: Projection,
           scaler: ScalingShifter,
           location: EarthLocation,
           catalogue: Catalogue,
           fragments: list[SkyPointSource],
           i, timestamp: Time,
           directory: Path) -> int:

    # This is needed so that noise is not generated using the same seed across workers
    np.random.seed((os.getpid() * int(time.time())) % 123456789)

    scene = Scene(xres, yres, projection=projection, scaler=scaler, location=location, catalogue=catalogue, time=timestamp)
    scene.build(fragments)

    scene.render_as_poisson()
    scene.add_intensifier_noise(100, 10, radius=70)
    scene.add_thermal_noise(rate=40)

    scene.render(directory / f'{i:03}.png')
    return 1


# Behind the guard, and it has to be. Python 3.14 starts subprocesses with forkserver rather than
# fork on Linux, so a Pool worker imports this module rather than inheriting a copy of it -- and an
# unguarded run() at module scope means every worker starts its own renderer, which comes back as
# a ConnectionResetError out of forkserver's handshake. Under fork it happened to work.
if __name__ == '__main__':
    simulator = MeteorRenderer().run()
